### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Altogolik** [GoobyCorp/DOOMSaveManager#2]
I converted the save, but it did not transfer my skins and lvl profiles, achievements. Only progress in pumping and plot was transferred.

**Comment by GoobyCorp** [comment]
Expected behavior, watch the cs.rin thread for other users who plan to release all skins, DLC, level profiles, etc. - the script transfers everything in your save folder, further research is underway

**Comment by Altogolik** [comment]
what kind of cs.rin where can I see? (link?)
