### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by stevethers** [GoobyCorp/DOOMSaveManager#8]
Please Please can you explain it to me like i am a 5 year old what to do... what to export where and import where, my transfer seems to have a "Wrong directory" Please help me out how do I decrypt encrypt

**Comment by stevethers** [comment]
Just to clarify I am using steam version.. My directory is steam/userdata/xxx/782330/remote/ and there are "PROFILE" and "GAME-AUTOSAVE1" so what do i do exactly to get it to transfer, import and export works but for my transfer I have this... https://gyazo.com/0e843738ba6fe84cfcb4f1de5e6a4ca0

**Comment by GoobyCorp** [comment]
That source should be your Steam ID64

**Comment by stevethers** [comment]
I figured it out saves from internet from other users who use steam ( for some reason do no transfer) however I downloaded save from a Bethesda launcher user and transferred it, it works great profile and the save. So that’s that.
