### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by scooterlord** [GoobyCorp/DOOMSaveManager#9]
Hello and thanks for the efforts. Getting the following error - any ideas?

Unhandled exception has occurred in your application. If you click Continue. the application will ignore this error and attempt to continue. If you click Quit. the application will close immediately.

The type initializer for 'DOOMSaveManager.DoomEternal' threw an exception.

Below is the error:
https://pastebin.com/cRKpeV4J

**Comment by GoobyCorp** [comment]
Try the new release (1.3.0.5 as of writing)

**Comment by scooterlord** [comment]
@GoobyCorp thanks for the fast reply! Same error message again.. although you can continue, fields are empty..

**Comment by scooterlord** [comment]
@GoobyCorp Same issue on my laptop as well. Windows 10 Pro here as well - .NET preinstalled.
